### ISSUE TITLE
Text element support

### ISSUE THREAD

**Issue by topochico-one** [typst/svg2pdf#16]
Thanks for creating svg2pdf! Does it support text elements? I get a blank PDF when I try to convert the following SVG:

```svg
<?xml version="1.0"?>
<svg xmlns="http://www.w3.org/2000/svg" 
     xmlns:xlink="http://www.w3.org/1999/xlink" 
     width="600" height="300">
<text x="0" y="15" fill="red">I love SVG</text>
</svg>
```

**Comment by laurmaedje** [comment]
`svg2pdf` uses `usvg` behind the scenes to convert the SVG to a simpler representation. This also includes converting text to curves. So to correctly render text, you have to manually create a `usvg::Tree` from your string ([providing fonts](https://docs.rs/usvg/0.23.0/usvg/struct.Options.html#structfield.fontdb)) and then use `convert_tree` instead of `convert_str`. You can see how it's done in svg2pdf's CLI [here](https://github.com/typst/svg2pdf/blob/bd09bea1b4c5926b33ad1f446678b74fbb0dafec/src/main.rs#L39).

**Comment by laurmaedje** [comment]
This should probably be explained in the documentation, we can keep this issue open to track that.

**Comment by topochico-one** [comment]
Ah this makes sense! Thank you for the super fast response!
