### ISSUE TITLE
Messed up transformation of groups

### ISSUE THREAD

**Issue by EQt** [typst/svg2pdf#9]
See for [example](https://github.com/EQt/svg2pdf/blob/main/tests/clip_line.svg): The clip path is not transformed in the PDF.

The bug also appears sometimes for `<image>` in a `<g>`roup.

**Comment by EQt** [comment]
I debugged a lot to understand the code structure and find a workaround in my [debug branch](https://github.com/eqt/svg2pdf/tree/debug). It works for `clip_line.svg` example above but messes up on other instances, e.g. the `tests/example.svg`.

Any ideas on why the code fails?

**Comment by reknih** [comment]
Hey!
Sorry for the late response. Unfortunately, I don't have the bandwidth right now to fix this issue. The culprit could be that the group code seems to be doing nothing with the transform it's been given at all --- but the whole transform handling could be made more robust.

Eventually, I want to fix this by using transform matrices in the PDF content stream more rather than the pre-baked coordinates using the `CoordToPdf` struct ...
